version: "3"

services:
    db:
        image: mysql/mysql-server:5.7
        tty: true
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: trading_club
        ports:
            - "3308:3306"

    crawler:
        build:
            context: .
            dockerfile: docker/python.dockerfile
        ports:
            - 3005:3000
        volumes:
            - .:/app
        tty: true
        depends_on:
        - "db"
        links:
            - db:db

