version: "3"

services:
    db:
        image: mysql/mysql-server:5.7
        tty: true
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: jim
            MYSQL_PASSWORD: jim
            MYSQL_DATABASE: trading_club
        ports:
            - "3308:3306"
        volumes:
            - ./data:/var/lib/mysql
        healthcheck:
            test: ["CMD-SHELL", "mysql --connect-timeout=1 -u root -proot -e \"select 1;\" > /dev/null 2>&1 || exit 1"]
            interval: 30s
            timeout: 10s
            retries: 3

    crawler:
        build:
            context: .
            dockerfile: docker/python.dockerfile
        ports:
            - 3005:3000
        volumes:
            - .:/app
        tty: true
        depends_on:
            - db
            - selenium-hub
        links:
            - db:db
            - selenium-hub:selenium-hub


    selenium-hub:
        image: selenium/hub:3.141.59-zinc
        container_name: selenium-hub
        ports:
            - "4444:4444"
        healthcheck:
            test: "curl -f http://localhost:4444 || false"
            interval: 30s
            timeout: 10s
            retries: 3

    chrome:
        image: selenium/node-chrome:3.141.59-zinc
        volumes:
            - ./web-driver:/dev/shm
        depends_on:
            - selenium-hub
        environment:
            - HUB_HOST=selenium-hub
            - HUB_PORT=4444
