KRX = 'http://global.krx.co.kr/contents/GLB/05/0503/0503010200/GLB0503010200.jsp'
N225 = 'https://indexes.nikkei.co.jp/en/nkave/index/component'
TOPIX = 'https://www.jpx.co.jp/english/markets/indices/topix/'
SCHCOMP = 'http://www.sse.com.cn/market/sseindex/indexlist/s/i000001/const_list.shtml'
TAIFEX = 'https://www.taifex.com.tw/cht/9/futuresQADetail'
TWOTC = 'https://www.tpex.org.tw/web/stock/iNdex_info/index/consti_result.php?l=zh-tw&d=108/12/19&s=0,asc,0&o=htm'
YAHOO = 'https://finance.yahoo.com/quote/005930.KS?p='
